# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPanel_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("image: url(:/luxshare/luxshare.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 38, 0);\n"
"font: 75 36pt \"Helvetica\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 14pt \"Helvetica\";")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_2.setStyleSheet("*{font: 75 28pt \"Helvetica\";}\n"
"\n"
".QLineEdit{\n"
"background-color: rgb(131, 151, 180);\n"
"border:0px solid red;\n"
"}\n"
".QLineEdit::hover{\n"
"    background-color: rgb(240, 233, 94);\n"
"border:0px solid red;\n"
"}")
        self.verticalFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_5.setStyleSheet("background-color: rgb(131, 151, 180);")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_6.setStyleSheet("background-color: rgb(106, 255, 253);")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.verticalFrame_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formFrame = QtWidgets.QFrame(self.centralwidget)
        self.formFrame.setStyleSheet(".QLabel{\n"
"font: 14pt \"Helvetica\";\n"
"}\n"
".QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(99, 229, 255);\n"
"    min-height:40px;\n"
"    max-height:40px\n"
"}\n"
".QPushButton::hover{\n"
"    border-radius:9px;\n"
"    background-color: orange;\n"
"    min-height:40px;\n"
"    max-height:40px\n"
"}\n"
".QPushButton:pressed{\n"
"    border-radius:9px;\n"
"    background-color: rgb(200, 229, 255);\n"
"    min-height:40px;\n"
"    max-height:40px\n"
"}")
        self.formFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(10, -1, 10, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lb_pass = QtWidgets.QLabel(self.formFrame)
        self.lb_pass.setMinimumSize(QtCore.QSize(60, 0))
        self.lb_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pass.setObjectName("lb_pass")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lb_pass)
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        self.label_9.setMinimumSize(QtCore.QSize(60, 0))
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lb_fail = QtWidgets.QLabel(self.formFrame)
        self.lb_fail.setMinimumSize(QtCore.QSize(60, 0))
        self.lb_fail.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_fail.setObjectName("lb_fail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lb_fail)
        self.label_11 = QtWidgets.QLabel(self.formFrame)
        self.label_11.setMinimumSize(QtCore.QSize(60, 0))
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lb_yield = QtWidgets.QLabel(self.formFrame)
        self.lb_yield.setMinimumSize(QtCore.QSize(60, 0))
        self.lb_yield.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_yield.setObjectName("lb_yield")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lb_yield)
        self.horizontalLayout_3.addWidget(self.formFrame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tracking Flex Plugin"))
        self.label_2.setText(_translate("MainWindow", "By SMT  TE"))
        self.label_7.setText(_translate("MainWindow", "Pass Qty:"))
        self.lb_pass.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Fail Qty:"))
        self.lb_fail.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Yield:"))
        self.lb_yield.setText(_translate("MainWindow", "100%"))
from Resource.img import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
